version: '3.8'
services:
  app:
    image: openjdk:11
    container_name: app
    ports:
      - 8080:8080
    tty: true
    volumes:
      - ./backend:/srv:cached
    working_dir: /srv
    depends_on:
      - db
    env_file:
      - ./.env

  db:
    image: oracle/database:19.3.0-ee
    container_name: oracle
    ports:
      - 1521:${INNER_DB_PORT_NO}
      - 5500:5500
    volumes:
      - ./oradata:/opt/oracle/oradata
      - ./startup:/opt/oracle/scripts/startup
    environment:
      - ORACLE_PDB=${ORACLE_PDB}
      - ORACLE_PWD=${ORACLE_PWD}
      - ORACLE_CHARACTERSET=${ORACLE_CHARACTERSET}
