ALTER SESSION SET CONTAINER = ORCLPDB1;
CONNECT BOOK_SHOP/booker@ORCLPDB1

---------------------------------------------------------------------------
-- execute the following statements to create tables
---------------------------------------------------------------------------
-- events
CREATE TABLE events
  (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY
    START WITH 1 PRIMARY KEY,
    description VARCHAR2(255) NOT NULL,
    published NUMBER(1) NOT NULL CHECK  (published in (0,1)),
    title VARCHAR2(255) NOT NULL
  );

COMMIT;
exit;
